version: "3.3"

services:
  faunadb:
    image: fauna/faunadb
    container_name: faunadb
    ports:
      - "8443:8443"

  node-lts:
    image: node:18.15-alpine3.16
    container_name: node-lts
    depends_on:
      - faunadb
    volumes:
      - "../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_SCHEME: http
      FAUNA_DOMAIN: faunadb
      FAUNA_PORT: 8443
      FAUNA_SECRET: secret
      FAUNA_ENDPOINT: http://faunadb:8443
    command:
      - /bin/sh
      - -cxe
      - |
        apk add --no-cache curl
        ./concourse/scripts/wait-for-it.sh http://faunadb:8443/ping
        npm install
        npm run test
        npm run examples
